version: '3.9'
services: 
    webserver:
        image: arjunraghava/webapp:0.1
        ports: 
            - 55000:80
        deploy:
            mode: replicated
            replicas: 1
       
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
